name: Build executable file

on:
  workflow_dispatch:

jobs:

  Build:
    strategy:
      fail-fast: false
      matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.2.0
      - name: Set up Python 3.11
        uses: actions/setup-python@v4.3.1
        with:
          python-version: "3.11"
          cache: pip
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python release.py --install
      - name: Build executable file
        shell: bash
        run: |
          title=$(python release.py --title)
          echo "title=${title}"
          echo "title=${title}" >> $GITHUB_ENV
          path=$(python release.py --path)
          echo "path=${path}"
          echo "path=${path}" >> $GITHUB_ENV
          python release.py --build
      - name: Upload executable file
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ${{ env.title }}
          path: ${{ env.path }}
