name: Code checks

on:
  push:

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.2.0
      with:
        submodules: 'true'
        token: ${{ secrets.SPEICAL_TOKEN }}
    - name: Set up Python 3.12
      uses: actions/setup-python@v4.3.1
      with:
        python-version: "3.12"
    - name: Cache pip packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r development_requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
        with:
          submodules: 'true'
          token: ${{ secrets.SPEICAL_TOKEN }}
      - name: Set up Python 3.12
        uses: actions/setup-python@v4.3.1
        with:
          python-version: "3.12"
      - name: Cache pip packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r development_requirements.txt
      - name: Analysing the code with pycodestyle
        run: |
          pycodestyle $(git ls-files '*.py')

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
        with:
          submodules: 'true'
          token: ${{ secrets.SPEICAL_TOKEN }}
      - name: Set up Python 3.12
        uses: actions/setup-python@v4.3.1
        with:
          python-version: "3.12"
      - name: Cache pip packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r development_requirements.txt
      - name: Extract secrets
        run: |
          mkdir -p database
          rm -rf database/user_data.txt
          touch database/user_data.txt
          echo ${{ secrets.USERNAME_LEVNET }} >> database/user_data.txt
          echo ${{ secrets.PASSWORD_LEVNET }} >> database/user_data.txt
      - name: Run pytest
        run: |
          export JUPYTER_PLATFORM_DIRS=1
          jupyter --paths
          coverage run --rcfile=".coveragerc_ci_cd" -m pytest $(git ls-files 'test_*.py') -s -v -m "not network"
      - name: Run coverage
        run: |
          coverage report --rcfile=".coveragerc_ci_cd" -m --omit="./semester_organizer_private/network/network.py,./collector/network/public_network.py" --fail-under=100
