name: Generate constraint json data

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  UpdateNewGenerated:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.2.0
      with:
        submodules: 'true'
        token: ${{ secrets.SPEICAL_TOKEN }}
    - name: Set up Python 3.12
      uses: actions/setup-python@v4.3.1
      with:
        python-version: "3.12"
    - name: Cache pip packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r development_requirements.txt
    - name: Clear and create log file
      run: |
        rm -rf log.txt
        touch log.txt
    - name: Extract secrets
      shell: bash
      run: |
        mkdir -p database
        rm -rf database/user_data.txt
        touch database/user_data.txt
        echo ${{ secrets.USERNAME_LEVNET }} >> database/user_data.txt
        echo ${{ secrets.PASSWORD_LEVNET }} >> database/user_data.txt
    - name: Run python update script flow
      run: |
        python main.py --flow update_generated_json_data
    - name: Commit changes if there are
      id: commit_changes
      run: |
        git config --local user.email "itamar1111111@gmail.com"
        git config --local user.name "Itamar Shalev"
        find algorithms/generated_data -type f | grep -v "personal" | xargs git add --force
        if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit."
            echo "should_push=false" >> $GITHUB_OUTPUT
        else
            git commit -sm "[AUTO] algorithms: Generate constraint courses json data."
            echo "Changes committed."
            echo "should_push=true" >> $GITHUB_OUTPUT
        fi
    - name: Push to main
      if: ${{ steps.commit_changes.outputs.should_push == 'true' }}
      uses: CasperWA/push-protected@v2
      with:
        token: ${{ secrets.SPEICAL_TOKEN }}
        branch: main
        force: True
