name: Test all tests on all platforms

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0,2,4'

jobs:

  Test:
    strategy:
      fail-fast: false
      matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
          python-version: ["3.11", "3.10", "3.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.2.0
        with:
          submodules: 'true'
          token: ${{ secrets.SPEICAL_TOKEN }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.3.1
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r development_requirements.txt
      - name: Extract secrets
        shell: bash
        run: |
          mkdir -p database
          rm -rf database/user_data.txt
          touch database/user_data.txt
          echo ${{ secrets.USERNAME_LEVNET }} >> database/user_data.txt
          echo ${{ secrets.PASSWORD_LEVNET }} >> database/user_data.txt
      - name: Run pytest
        run: |
          pytest $(git ls-files 'test_*.py') -v -m "not network_driver" --reruns 2 --reruns-delay 5
