name: Update data cycle

on:
  workflow_dispatch:

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.2.0
      with:
        submodules: 'true'
        token: ${{ secrets.SPEICAL_TOKEN }}
    - name: Set up Python 3.11
      uses: actions/setup-python@v4.3.1
      with:
        python-version: "3.11"
        cache: pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r development_requirements.txt
    - name: Clear and create log file
      run: |
        rm -rf log.txt
        touch log.txt
    - name: Extract secrets
      shell: bash
      run: |
        mkdir -p database
        rm -rf database/user_data.txt
        touch database/user_data.txt
        echo ${{ secrets.USERNAME_LEVNET }} >> database/user_data.txt
        echo ${{ secrets.PASSWORD_LEVNET }} >> database/user_data.txt
    - name: Run python update script flow
      run: |
        python update_levnet_data.py
    - name: Commit changes
      run: |
        git config --local user.email "itamar1111111@gmail.com"
        git config --local user.name "Itamar Shalev"
        git add database/database.db --force
        git commit -sm "[DATA] database: Update levnet courses data ."
    - name: Push to main
      uses: CasperWA/push-protected@v2
      with:
        token: ${{ secrets.SPEICAL_TOKEN }}
        branch: main
        force: True
