name: Update data cycle

on:
  workflow_dispatch:

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.2.0
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Clear and create log file
      run: |
        rm -rf log.txt
        touch log.txt
    - name: Run python update script flow
      run: |
        python update_levnet_data.py
    - name: Commit changes
      run: |
        git config --local user.email "itamar1111111@gmail.com"
        git config --local user.name "Itamar Shalev"
        git add . --force
        git commit -sm "[BOT] Update levnet courses data."
    - name: Push to main
      uses: CasperWA/push-protected@v2
      with:
        token: ${{ secrets.SPEICAL_TOKEN }}
        branch: main
